% run under the .../sub-01/SUMA/

#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Create LayNii rim + 3 layers in native T1 space
# Uses SUMA outputs produced by @SUMA_Make_Spec_FS
# Recommended: use existing lh.ribbon.nii.gz / rh.ribbon.nii.gz
# ============================================================

# --- Working directory: SUMA folder ---
# Example:
# cd /data/p_03179/Kenshu_Resting/derivatives/fastsurfer/sub-01/SUMA

# Reference grid (native T1 space)
T1="T1.nii.gz"

# Output directory
OUTDIR="layers_nativeT1"
mkdir -p "${OUTDIR}"

echo "[INFO] Using reference grid: ${T1}"
echo "[INFO] Output directory: ${OUTDIR}"

# ------------------------------------------------------------
# 1) Create WM and Pial surface masks in T1 grid
#    (Use the simple non-std surfaces that are already present.)
# ------------------------------------------------------------
echo "[INFO] Creating surface masks (WM / Pial) in T1 space..."

3dSurf2Vol \
  -spec sub-01_lh.spec \
  -surf_A lh.pial.gii \
  -map_func mask \
  -gridset "${T1}" \
  -sv "${T1}" \
  -prefix "${OUTDIR}/lh.pial_vol.nii.gz" \
  -overwrite

3dSurf2Vol \
  -spec sub-01_lh.spec \
  -surf_A lh.smoothwm.gii \
  -map_func mask \
  -gridset "${T1}" \
  -sv "${T1}" \
  -prefix "${OUTDIR}/lh.wm_vol.nii.gz" \
  -overwrite

3dSurf2Vol \
  -spec sub-01_rh.spec \
  -surf_A rh.pial.gii \
  -map_func mask \
  -gridset "${T1}" \
  -sv "${T1}" \
  -prefix "${OUTDIR}/rh.pial_vol.nii.gz" \
  -overwrite

3dSurf2Vol \
  -spec sub-01_rh.spec \
  -surf_A rh.smoothwm.gii \
  -map_func mask \
  -gridset "${T1}" \
  -sv "${T1}" \
  -prefix "${OUTDIR}/rh.wm_vol.nii.gz" \
  -overwrite

# Merge hemispheres
3dcalc -a "${OUTDIR}/lh.pial_vol.nii.gz" -b "${OUTDIR}/rh.pial_vol.nii.gz" \
  -expr 'a+b' -prefix "${OUTDIR}/pial_vol.nii.gz" -overwrite

3dcalc -a "${OUTDIR}/lh.wm_vol.nii.gz" -b "${OUTDIR}/rh.wm_vol.nii.gz" \
  -expr 'a+b' -prefix "${OUTDIR}/wm_vol.nii.gz" -overwrite

# ------------------------------------------------------------
# 2) Build ribbon/fill mask
#    Use existing ribbon volumes generated by SUMA:
#      lh.ribbon.nii.gz + rh.ribbon.nii.gz
# ------------------------------------------------------------
echo "[INFO] Creating ribbon/fill mask from existing lh.ribbon / rh.ribbon..."

if [[ ! -f "lh.ribbon.nii.gz" || ! -f "rh.ribbon.nii.gz" ]]; then
  echo "[ERROR] Missing lh.ribbon.nii.gz or rh.ribbon.nii.gz in SUMA directory."
  echo "        They appear in your ls output, so this should not happen."
  exit 1
fi

3dcalc -a lh.ribbon.nii.gz -b rh.ribbon.nii.gz \
  -expr 'step(a)+step(b)' \
  -prefix "${OUTDIR}/fill.nii.gz" -overwrite

# ------------------------------------------------------------
# 3) Create LayNii rim file (same logic as Kenshu script)
#    rim coding:
#      1 = pial boundary
#      2 = WM boundary
#      3 = GM ribbon (fill)
# ------------------------------------------------------------
echo "[INFO] Creating LayNii rim file..."

3dcalc \
  -a "${OUTDIR}/fill.nii.gz" \
  -b "${OUTDIR}/wm_vol.nii.gz" \
  -c "${OUTDIR}/pial_vol.nii.gz" \
  -expr 'step(c)+step(b)*2+3*step(a)-and(a,b)*3-and(a,c)*3' \
  -prefix "${OUTDIR}/rim.nii.gz" \
  -overwrite

# ------------------------------------------------------------
# 4) Layerification: 3 layers (+ borders if requested)
# ------------------------------------------------------------
echo "[INFO] Running LN2_LAYERS for 3 layers..."

LN2_LAYERS \
  -rim "${OUTDIR}/rim.nii.gz" \
  -nr_layers 3 \
  -incl_borders \
  -output "${OUTDIR}/layers_3.nii.gz"

echo ""
echo "[DONE]"
echo "  rim:    ${OUTDIR}/rim.nii.gz"
echo "  layers: ${OUTDIR}/layers_3.nii.gz"
